spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_test
    username: myuser
    password: mypassword

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

logging:
  level:
    org.hibernate.sql: debug

jwt:
  issuer: ssafy@ssafy.com
  secret_key: studyspringbootstudyspringbootstudyspringbootstudyspringbootstudyspringboot

